########################################################################
# RQG integration tests with DML and DDL, different engines.
# The default set is big bang, but it can be narrowed down through
# configuration parameters
########################################################################

trigger: none

variables:

  CMAKE_BUILD_TYPE: Debug
  CMAKE_OPTIONS: "-DPLUGIN_SPHINX=NO -DPLUGIN_OQGRAPH=NO -DPLUGIN_TOKUDB=NO -DPLUGIN_MROONGA=NO -DPLUGIN_FEDERATED=NO -DPLUGIN_FEDERATEDX=NO -DPLUGIN_CONNECT=NO -DPLUGIN_SPIDER=NO -DPLUGIN_ROCKSDB=NO -DWITH_MARIABACKUP=OFF"

  RQG_DURATION: 400
  RQG_THREADS: 6
  RQG_VIEWS: '--views'

  # --redefine=conf/mariadb/modules/acl.yy disabled due to MDEV-18003
  RQG_REDEFINES: "\
    --redefine=conf/mariadb/bulk_insert.yy \
    --redefine=conf/mariadb/modules/sql_mode.yy \
    --redefine=conf/mariadb/alter_table.yy \
    --redefine=conf/mariadb/instant_add.yy \
    --redefine=conf/mariadb/modules/alter_table_columns.yy \
    --redefine=conf/mariadb/modules/foreign_keys.yy \
    --redefine=conf/mariadb/sp.yy \
    --redefine=conf/mariadb/modules/userstat.yy \
    --redefine=conf/mariadb/modules/admin.yy \
    --redefine=conf/mariadb/modules/locks.yy \
    --redefine=conf/mariadb/versioning.yy \
    --redefine=conf/mariadb/sequences.yy \
    --redefine=conf/mariadb/modules/locks-10.4-extra.yy \
  "
  RQG_OPTIONS: "\
    --seed=time \
    --reporters=Backtrace,ErrorLog,Deadlock \
    --filter=conf/mariadb/10.4-combo-filter.ff \
  "
  MYSQLD_OPTIONS: "\
    --mysqld=--log_output=FILE \
    --mysqld=--loose-max-statement-time=20 \
    --mysqld=--lock-wait-timeout=10 \
    --mysqld=--loose-innodb-lock-wait-timeout=5 \
    --mysqld=--loose-debug_assert_on_not_freed_memory=0 \
  "

jobs:

#########
# Download or build server
- template: jobs/prepare-server.yml
  parameters:
    name: 'Download_or_Build_Server'

#########
# Upload to FTP
- template: jobs/upload-to-ftp.yml
  parameters:
    dependencies:
    - 'Download_or_Build_Server'
    condition: and(succeeded(), ne(dependencies.Download_or_Build_Server.outputs['ftp_download.BINARIES_FROM_FTP'], 'true'))

#########
- job: Test
  dependsOn: Download_or_Build_Server
  pool:
    vmImage: 'Ubuntu 16.04'

  strategy:
    matrix:

      'test001':
        RQG_GRAMMAR: 'conf/runtime/metadata_stability.yy'
        RQG_GENDATA: 'conf/runtime/metadata_stability.zz'

      'test002':
        RQG_GRAMMAR: 'conf/runtime/performance_schema.yy'
        MYSQLD_EXTRA_OPTIONS: '--mysqld=--performance-schema'

      'test003':
        RQG_GRAMMAR: 'conf/runtime/information_schema.yy'

      'test004':
        RQG_GRAMMAR: 'conf/engines/many_indexes.yy'
        RQG_GENDATA: 'conf/engines/many_indexes.zz'
        RQG_ENGINE: InnoDB

      'test005':
        RQG_GRAMMAR: 'conf/engines/many_indexes.yy'
        RQG_GENDATA: 'conf/engines/many_indexes.zz'
        RQG_ENGINE: Aria

      'test006':
        RQG_GRAMMAR: 'conf/engines/engine_stress.yy'
        RQG_GENDATA: 'conf/engines/engine_stress.zz'
        RQG_ENGINE: InnoDB

      'test007':
        RQG_GRAMMAR: 'conf/engines/engine_stress.yy'
        RQG_GENDATA: 'conf/engines/engine_stress.zz'
        RQG_ENGINE: Aria

      'test008':
        RQG_GRAMMAR: 'conf/engines/engine_stress.yy'
        RQG_GENDATA: 'conf/engines/engine_stress.zz'
        RQG_ENGINE: MyISAM

      'test009':
        RQG_GRAMMAR: 'conf/partitioning/partitions.yy'
        RQG_ENGINE: InnoDB

      'test010':
        RQG_GRAMMAR: 'conf/partitioning/partition_pruning.yy'
        RQG_GENDATA: 'conf/partitioning/partition_pruning.zz'
        RQG_ENGINE: InnoDB

      'test011':
        RQG_GRAMMAR: 'conf/replication/replication.yy'
        RQG_GENDATA: 'conf/replication/replication-5.1.zz'
        RQG_ENGINE: InnoDB

      'test012':
        RQG_GRAMMAR: 'conf/replication/replication-ddl_sql.yy'
        RQG_GENDATA: 'conf/replication/replication-ddl_data.zz'
        RQG_ENGINE: InnoDB

      'test013':
        RQG_GRAMMAR: 'conf/replication/replication-dml_sql.yy'
        RQG_GENDATA: 'conf/replication/replication-dml_data.zz'
        RQG_ENGINE: InnoDB

      'test014':
        RQG_GRAMMAR: 'conf/runtime/connect_kill_sql.yy'
        RQG_GENDATA: 'conf/runtime/connect_kill_data.zz'
        RQG_ENGINE: InnoDB

      'test015':
        RQG_GRAMMAR: 'conf/runtime/WL5004_sql.yy'
        RQG_GENDATA: 'conf/runtime/WL5004_data.zz'
        RQG_ENGINE: InnoDB

      'test016':
        RQG_GRAMMAR: 'conf/mariadb/optimizer.yy'
        RQG_ENGINE: InnoDB

      'test017':
        RQG_GRAMMAR: 'conf/mariadb/optimizer.yy'
        RQG_ENGINE: Aria

      'test018':
        RQG_GRAMMAR: 'conf/mariadb/optimizer.yy'
        RQG_ENGINE: MyISAM

      'test019':
        RQG_GRAMMAR: 'conf/optimizer/updateable_views.yy'
        RQG_EXTRA_OPTIONS: '--skip-gendata'
        MYSQLD_EXTRA_OPTIONS: "--mysqld=--init-file=$ENV_RQG_HOME/conf/optimizer/updateable_views.init --mysqld=--default-storage-engine=MyISAM"
        RQG_ENGINE: MyISAM

      'test020':
        RQG_GRAMMAR: 'conf/mariadb/oltp-transactional.yy'
        RQG_GENDATA: 'conf/mariadb/oltp.zz'
        RQG_ENGINE: InnoDB

      'test021':
        RQG_GRAMMAR: 'conf/mariadb/oltp-transactional.yy'
        RQG_GENDATA: 'conf/mariadb/oltp.zz'
        RQG_ENGINE: Aria

      'test022':
        RQG_GRAMMAR: 'conf/mariadb/oltp.yy'
        RQG_GENDATA: 'conf/mariadb/oltp.zz'
        RQG_ENGINE: MyISAM

      'test023':
        RQG_GRAMMAR: 'conf/mariadb/functions.yy'

      'test024':
        RQG_GRAMMAR: 'conf/runtime/alter_online.yy'
        RQG_GENDATA: 'conf/runtime/alter_online.zz'

      'test025':
        RQG_GRAMMAR: 'conf/engines/innodb/full_text_search.yy'
        RQG_GENDATA: 'conf/engines/innodb/full_text_search.zz'
        RQG_ENGINE: InnoDB

      'test026':
        RQG_GRAMMAR: 'conf/engines/innodb/full_text_search.yy'
        RQG_GENDATA: 'conf/engines/innodb/full_text_search.zz'
        RQG_ENGINE: MyISAM

      'test027':
        RQG_GRAMMAR: 'conf/engines/innodb/full_text_search.yy'
        RQG_GENDATA: 'conf/engines/innodb/full_text_search.zz'
        RQG_ENGINE: Aria

      'test028':
        RQG_GRAMMAR: 'conf/engines/heap/heap_dml_single.yy'
        RQG_EXTRA_OPTIONS: '--skip-gendata'
        MYSQLD_EXTRA_OPTIONS: "--mysqld=--init-file=$ENV_RQG_HOME/conf/engines/heap/heap_dml_single.init"

      'test029':
        RQG_GRAMMAR: 'conf/engines/heap/heap_ddl_multi.yy'
        RQG_EXTRA_OPTIONS: '--skip-gendata'

      'test030':
        RQG_GRAMMAR: 'conf/temporal/temporal_functions.yy'
        RQG_GENDATA: 'conf/temporal/temporal_functions.zz'
        RQG_ENGINE: InnoDB

      'test031':
        RQG_GRAMMAR: 'conf/temporal/temporal_functions.yy'
        RQG_GENDATA: 'conf/temporal/temporal_functions.zz'
        RQG_ENGINE: MyISAM

      'test032':
        RQG_GRAMMAR: 'conf/temporal/temporal_functions.yy'
        RQG_GENDATA: 'conf/temporal/temporal_functions-wl946.zz'
        RQG_DURATION: 1200

      'test033':
        RQG_GRAMMAR: 'conf/mariadb/generic-dml.yy'
        RQG_GENDATA: '--gendata-advanced'
        RQG_EXTRA_OPTIONS: '--skip-gendata'
        RQG_ENGINE: InnoDB

      'test034':
        RQG_GRAMMAR: 'conf/mariadb/generic-dml.yy'
        RQG_GENDATA: '--gendata-advanced'
        RQG_EXTRA_OPTIONS: '--skip-gendata'
        RQG_ENGINE: MyISAM

      'test035':
        RQG_GRAMMAR: 'conf/mariadb/generic-dml.yy'
        RQG_GENDATA: '--gendata-advanced'
        RQG_EXTRA_OPTIONS: '--skip-gendata'
        RQG_ENGINE: Aria

      'test036':
        RQG_GRAMMAR: 'conf/mariadb/generic-dml.yy'
        RQG_GENDATA: '--gendata-advanced'
        RQG_EXTRA_OPTIONS: '--skip-gendata'
        RQG_ENGINE: HEAP

  steps:

  - template: steps/env.yml

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: 'build'
      downloadPath: $(Build.ArtifactStagingDirectory)
    displayName: 'Download build from artifacts'

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/build/build-*.tar.gz'
      destinationFolder: $(env.BASEDIR)
    displayName: 'Extract build'

  - template: steps/install-runtime-packages.yml

  - template: steps/clone-test-tools.yml

  - template: steps/run-rqg-test.yml

#########
# Print summary
- template: jobs/test-summary.yml
  parameters:
    dependencies:
    - Test
