# Test different steps and configurations without running big jobs

trigger: none

jobs:

#- job: test
#  steps: 
#  - script: |
#      echo "opt1: $OPT1 opt2: $OPT2 opt3: $OPT3 opt4: $OPT4"
#      echo opt1: $(opt1) opt2: $(opt2) opt3: $(opt3) opt4: $(opt4)
#      echo "opt1: $OOPT1 opt2: $OOPT2 opt3: $OOPT3 opt4: $OOPT4"
#    env:
#      OOPT1: $(opt1)
#      OOPT2: $(opt2)
#      OOPT3: $(opt3)
#      OOPT4: $(opt4)

#jobs:
- template: jobs/setenv.yml
  parameters:
    name: setenv
    taskname: env
    rqgOptions: '--duration=300'

- job: check_after_job
  dependsOn: setenv
  steps:
  - script: |
      echo serverBranch: $(serverBranch)
      echo rqgBranch: $(rqgBranch)
      echo toolboxBranch: $(toolboxBranch)
      echo cmakeOptions: $(cmakeOptions)
      echo rqgOptions: $(rqgOptions)
      echo mysqldOptions: $(mysqldOptions)
      echo baseDir: $(baseDir)
      echo toolboxDir: $(toolboxDir)
      echo rqgHome: $(rqgHome)
      echo logDir: $(logDir)
  variables:
    serverBranch: $[ dependencies.setenv.outputs['env.serverBranch' ] ]
    rqgBranch: $[ dependencies.setenv.outputs['env.rqgBranch' ] ]
    toolboxBranch: $[ dependencies.setenv.outputs['env.toolboxBranch' ] ]
    cmakeOptions: $[ dependencies.setenv.outputs['env.cmakeOptions' ] ]
    rqgOptions: $[ dependencies.setenv.outputs['env.rqgOptions' ] ]
    mysqldOptions: $[ dependencies.setenv.outputs['env.mysqldOptions' ] ]
    baseDir: $[ dependencies.setenv.outputs['env.baseDir' ] ]
    toolboxDir: $[ dependencies.setenv.outputs['env.toolboxDir' ] ]
    rqgHome: $[ dependencies.setenv.outputs['env.rqgHome' ] ]
    logDir: $[ dependencies.setenv.outputs['env.logDir' ] ]

- job: check_after_task
  steps:
  - template: steps/env.yml
    parameters:
      name: env
  - script: |
      echo serverBranch: $(serverBranch)
      echo rqgBranch: $(rqgBranch)
      echo toolboxBranch: $(toolboxBranch)
      echo cmakeOptions: $(cmakeOptions)
      echo rqgOptions: $(rqgOptions)
      echo mysqldOptions: $(mysqldOptions)
      echo baseDir: $(baseDir)
      echo toolboxDir: $(toolboxDir)
      echo rqgHome: $(rqgHome)
      echo logDir: $(logDir)


#jobs:
#- template: jobs/prepare-server.yml
#  parameters:
#    name: 'Download_or_Build_Server'
#    serverBranch: $(serverBranch)
#    cmakeOptions: '-DPLUGIN_CASSANDRA=NO -DPLUGIN_CONNECT=NO -DPLUGIN_FEDERATED=NO -DPLUGIN_FEDERATEDX=NO -DPLUGIN_MROONGA=NO -DPLUGIN_ROCKSDB=NO -DPLUGIN_SPHINX=NO -DPLUGIN_SPIDER=NO #-DPLUGIN_TOKUDB=NO -DWITH_MARIABACKUP=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_ASAN=NO'

#- template: jobs/upload-to-ftp.yml
#  parameters:
#    dependencies:
#    - 'Download_or_Build_Server'
