# Test different steps and configurations without running big jobs

trigger: none

jobs:

#- job: test
#  steps: 
#  - script: |
#      echo "opt1: $OPT1 opt2: $OPT2 opt3: $OPT3 opt4: $OPT4"
#      echo opt1: $(opt1) opt2: $(opt2) opt3: $(opt3) opt4: $(opt4)
#      echo "opt1: $OOPT1 opt2: $OOPT2 opt3: $OOPT3 opt4: $OOPT4"
#    env:
#      OOPT1: $(opt1)
#      OOPT2: $(opt2)
#      OOPT3: $(opt3)
#      OOPT4: $(opt4)

#jobs:
- template: jobs/setenv.yml
  parameters:
    name: setenv
    taskname: env
    rqgOptions: '--duration=300'

- job: check
  dependsOn: setenv
  steps:
  - template: steps/env.yml
  - script: |
      echo serverBranch: $(serverBranch)
      echo rqgBranch: $(rqgBranch)
      echo toolboxBranch: $(toolboxBranch)
      echo cmakeOptions: $(cmakeOptions)
      echo rqgOptions: $(rqgOptions)
      echo mysqldOptions: $(mysqldOptions)
      echo baseDir: $(baseDir)
      echo toolboxDir: $(toolboxDir)
      echo rqgHome: $(rqgHome)
      echo logDir: $(logDir)
