# Test different steps and configurations without running big jobs

trigger: none

jobs:
- template: jobs/prepare-server.yml
  parameters:
    serverBranch: '10.4'
    cmakeOptions: '-DCMAKE_BUILD_TYPE=Debug -DPLUGIN_ROCKSDB=NO -DPLUGIN_SPHINX=NO -DPLUGIN_SPIDER=NO -DPLUGIN_MROONGA=NO -DPLUGIN_TOKUDB=NO -DPLUGIN_FEDERATEDX=NO -DPLUGIN_CONNECT=NO -DPLUGIN_FEDERATED=NO -DWITH_MARIABACKUP=OFF'

- template: jobs/upload-to-ftp.yml
