########################################################################
# GCOV report for MTR tests
########################################################################

trigger: none

# Expects SERVER_BRANCH in the environment

jobs:

#########
- job: Build
  pool:
    vmImage: 'Ubuntu 16.04'
  timeoutInMinutes: 0
  strategy:
    parallel: 1

  steps:

  - template: steps/env.yml

  - template: steps/install-deb-packages.yml
    parameters:
      INSTALLATION_SET: 'all'
      EXTRA_PACKAGES: 'lcov'

  - bash: |
      set -x
      if [ -z "$ENV_SERVER_BRANCH" ]; then
        echo "##vso[task.complete result=Failed]\"SERVER_BRANCH\" has not been specified"
      else
        filename=gcov-last-revno.$ENV_SERVER_BRANCH
        if [ -n "$BASELINE_REVISION" ]; then
          baseline_revno=$BASELINE_REVISION
        elif wget $FTP_DOWNLOAD/$filename ; then
          baseline_revno=`cat $filename`
        fi
        if [ -z "$baseline_revno" ] ; then
          echo "##vso[task.complete result=Failed]Baseline revision has not been specified"
        else
          git clone $SERVER_REPO --branch=$ENV_SERVER_BRANCH $ENV_BASEDIR
          cd $ENV_BASEDIR
          current_revno=`git log -1 --abbrev=8 --pretty="%h"`
          echo "Baseline revision: $baseline_revno Current_revison: $current_revno"
          if [[ "$baseline_revno" =~ ^"$current_revno" ]] ; then
            echo "##vso[task.complete result=Skipped]Baseline revision is the same as current revision"
          else
            echo "##vso[task.setvariable variable=BASELINE_FILENAME;isOutput=true]$filename"
            echo "##vso[task.setvariable variable=BASELINE_REVISION;isOutput=true]$baseline_revno"
            echo "##vso[task.setvariable variable=INFODIR;isOutput=true]$HOME/gcov_info"
          fi
        fi
      fi
    displayName: 'Prepare and clone'
    env:
      FTP_DOWNLOAD: 'ftp://perro.askmonty.org/public/azure'
      SERVER_REPO: 'https://github.com/MariaDB/server'
    name: prep

  # Build the server in-source
  - bash: |
      set -x
      cd $ENV_BASEDIR
      cmake_options="$ENV_CMAKE_OPTIONS -DCMAKE_BUILD_TYPE=Debug -DENABLE_GCOV=ON"
      cmake . $cmake_options
      make -j5
      echo $ENV_SERVER_BRANCH `git log -1 --abbrev=8 --pretty="%h"` > $ENV_BASEDIR/server.info
      echo $cmake_options >> $ENV_BASEDIR/server.info
      cd $HOME
      tar zcf $BUILD_ARTIFACTSTAGINGDIRECTORY/build.tar.gz $ENV_BASEDIR
    displayName: 'Build'
    name: build_server

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: build

#########
- job: MTR_normal
  pool:
    vmImage: 'Ubuntu 16.04'
  timeoutInMinutes: 0
  dependsOn:
  - 'Build'
  strategy:
    parallel: 1

  steps:

  - template: steps/env.yml

  - download: current
    artifact: build

  - bash: |
      cd $HOME
      ls -l $PIPELINE_WORKSPACE
      ls -l $PIPELINE_WORKSPACE/build
      tar zxf $PIPELINE_WORKSPACE/build/build.tar.gz
      ls -l
      ls -l build
      mv build $ENV_BASEDIR
      cd $ENV_BASEDIR/mysql-test
      perl mysql-test-run.pl --mem --verbose-restart --force --max-test-fail=0 --retry=0
      cd $HOME
      rm build.tar.gz
      tar zcf $BUILD_ARTIFACTSTAGINGDIRECTORY/build.tar.gz $ENV_BASEDIR
    name: mtr_nm

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: build

#########
- job: MTR_ps
  pool:
    vmImage: 'Ubuntu 16.04'
  timeoutInMinutes: 0
  dependsOn:
  - 'Build'
  strategy:
    parallel: 1

  steps:

  - template: steps/env.yml

  - download: current
    artifact: build
    patterns: '**'

  - bash: |
      cd $HOME
      ls -l $PIPELINE_WORKSPACE
      tar zxf $PIPELINE_WORKSPACE/build.tar.gz
      ls -l
      ls -l build
      mv build $ENV_BASEDIR
      cd $ENV_BASEDIR/mysql-test
      perl mysql-test-run.pl --mem --verbose-restart --force --max-test-fail=0 --retry=0 --ps-protocol
      cd $HOME
      rm build.tar.gz
      tar zcf $BUILD_ARTIFACTSTAGINGDIRECTORY/build.tar.gz $ENV_BASEDIR
    name: mtr_ps

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: build

#########
- job: GCOV_report
  pool:
    vmImage: 'Ubuntu 16.04'
  timeoutInMinutes: 0
  strategy:
    parallel: 1
  dependsOn:
  - 'MTR_normal'
  - 'MTR_ps'

  steps:

  - template: steps/env.yml

  - download: current
    artifact: build

  - bash: |
      cd $HOME
      ls -l $PIPELINE_WORKSPACE
      tar zxf $PIPELINE_WORKSPACE/build.tar.gz
      ls -l
      ls -l build
      mv build $ENV_BASEDIR
      mkdir $PREP_INFODIR
      cd $HOME
      git clone https://github.com/elenst/mariadb-toolbox
      cd $ENV_BASEDIR
      git diff $PREP_BASELINE_REVISION > $PREP_INFODIR/gcov.diff
      lcov --rc lcov_branch_coverage=1 --quiet --directory $ENV_BASEDIR --capture --output-file $PREP_INFODIR/lcov.info
      perl $HOME/mariadb-toolbox/scripts/coverage_for_patch.pl --basedir=$ENV_BASEDIR --diff-file=$PREP_INFODIR/gcov.diff --lcov-info=$PREP_INFODIR/lcov.info --branch-info 1>coverage 2>missings
    name: gcov_report

  - publish: $(Prep.Infodir)
    artifact: gcov_info

  - publish: $(Prep.Filename)
    artifact: baseline

#########
# Upload to FTP
- template: jobs/upload-to-ftp.yml
  parameters:
    name: 'Upload_new_baseline_to_FTP'
    artifactName: 'baseline'
    dependencies:
    - 'GCOV_report'
    condition: succeeded()
