########################################################################
# Reproduce RQG failures observed elsewhere.
# The goal is to get the logs and binaries in the usual format,
# for further passing them to simplifiers
########################################################################

trigger: none

variables:

  SERVER_BRANCH: ''
  SERVER_REVISION: ''
  CMAKE_OPTIONS: ''
  RQG_OPTIONS: ''
  RQG_BRANCH: 'elenst-dev'
  TOOLBOX_BRANCH: 'master'

jobs:

#########
- job: Info
  steps:
    - script: |
      echo "#######################################################################"
      if [ -n "$_TEST_COMMENT" ] ; then
        echo $_TEST_COMMENT
        echo ""
      fi
      echo "SERVER_BRANCH:   $SERVER_BRANCH"
      echo "SERVER_REVISION: $SERVER_REVISION"
      echo "CMAKE_OPTIONS:   $CMAKE_OPTIONS"
      echo "RQG_OPTIONS:     $RQG_OPTIONS"
      echo "RQG_BRANCH:      $RQG_BRANCH"
      echo "TOOLBOX_BRANCH:  $TOOLBOX_BRANCH"
      echo "#######################################################################"

#########
# Download or build server
- template: jobs/prepare-server.yml
  parameters:
    name: 'Download_or_Build_Server'

#########
# Upload to FTP
- template: jobs/upload-to-ftp.yml
  parameters:
    dependencies:
    - 'Download_or_Build_Server'
    condition: and(succeeded(), ne(dependencies.Download_or_Build_Server.outputs['ftp_download.BINARIES_FROM_FTP'], 'true'))

#########
- job: Test
  dependsOn: Download_or_Build_Server
  pool:
    vmImage: 'Ubuntu 16.04'

  strategy:
    maxParallel: 2

  steps:
  - template: steps/env.yml

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: 'build'
      downloadPath: $(Build.ArtifactStagingDirectory)
    displayName: 'Download build from artifacts'

  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/build/build-*.tar.gz'
      destinationFolder: $(env.BASEDIR)
    displayName: 'Extract build'

  - template: steps/install-deb-packages.yml
    parameters:
      INSTALLATION_SET: 'runtime'

  - template: steps/clone-test-tools.yml

  - template: steps/run-rqg-test.yml

#########
# Print summary
- template: jobs/test-report.yml
  parameters:
    dependencies:
    - Test
