trigger: none

  # The general log is located in a different pipeline/build.
  #
  # TRIGGER_ID consists has a form of PipelineID-BuildId-ReproArtifactSuffix,
  # e.g. 10-837-20190220.1.003.1
  # Repro info is located in artifact test-<ReproArtifactSuffix>/repro-<ReproArtifactSuffix>
  # We don't require artifact name for the build, because it's always 'build'

  # Other parameters, which we (might) need in any case
  # SEARCH_PATTERN (needed for all practical purposes, although technically not mandatory)
  # MTR_OPTIONS (optional)
  # CONVERSION_OPTIONS (optional, --convert-to-ps and such)
  # SIMPLIFICATION_OPTIONS (optional, --mode, --max-chunk, --trials=X)
  # _TEST_COMMENT (optional, just a convenience for easier detecting what it was about)
  
jobs:

#########
- job: Simplify
  timeoutInMinutes: 0
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    parallel: 1

  steps:

  - script: |
      if [ -n "$_TEST_COMMENT" ] ; then
        echo "#####################"
        echo $_TEST_COMMENT
        echo "#####################"
      fi
      if [ -z "$TRIGGER_ID" ] ; then
        echo "##vso[task.complete result=Failed]\"TRIGGER_ID\" has not been specified"
      fi
      IFS='-' read -r -a ids <<< $TRIGGER_ID
      TRIGGERING_PIPELINE_ID=${ids[0]}
      TRIGGERING_BUILD_ID=${ids[1]}
      TRIGGERING_ARTIFACT_ID=${ids[2]}
      echo "##vso[task.setvariable variable=TRIGGERING_PIPELINE_ID]$TRIGGERING_PIPELINE_ID"
      echo "##vso[task.setvariable variable=TRIGGERING_BUILD_ID]$TRIGGERING_BUILD_ID"
      echo "##vso[task.setvariable variable=TRIGGERING_ARTIFACT_ID]$TRIGGERING_ARTIFACT_ID"
      echo "##vso[task.setvariable variable=BASEDIR]$HOME/server"
      echo "##vso[task.setvariable variable=RQG_HOME]$HOME/rqg"
      echo "##vso[task.setvariable variable=TOOLBOX_DIR]$HOME/toolbox"
      echo "Test comment:          " $_TEST_COMMENT
      echo "Search pattern:        " $SEARCH_PATTERN
      echo "Trigger ID:            " $TRIGGER_ID
      echo "Triggering pipeline ID:" $TRIGGERING_PIPELINE_ID
      echo "Triggering build ID:   " $TRIGGERING_BUILD_ID
      echo "Triggering artifact ID:" $TRIGGERING_ARTIFACT_ID
      echo "Conversion options:    " $CONVERSION_OPTIONS
      echo "Simplification options:" $SIMPLIFICATION_OPTIONS
      echo "MTR options:           " $MTR_OPTIONS
    displayName: 'Check configuration'

# Test info goes to a different dir, as we will only need a portion of it to republish
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'MariaDB tests'
      pipeline: '$(TRIGGERING_PIPELINE_ID)'
      buildVersionToDownload: 'specific'
      buildId: '$(TRIGGERING_BUILD_ID)'
      downloadType: 'single'
      artifactName: 'test-$(TRIGGERING_ARTIFACT_ID)'
      itemPattern: 'test-$(TRIGGERING_ARTIFACT_ID)/repro-$(TRIGGERING_ARTIFACT_ID)/**'
      downloadPath: '$(System.ArtifactsDirectory)'
    name: get_repro_info
    displayName: 'Download repro info from pipeline'

# The build goes directly to ArtifactsDirectory, as we'll need to publish it again
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'MariaDB tests'
      pipeline: '$(TRIGGERING_PIPELINE_ID)'
      buildVersionToDownload: 'specific'
      buildId: '$(TRIGGERING_BUILD_ID)'
      downloadType: 'single'
      artifactName: 'build'
      downloadPath: '$(System.ArtifactsDirectory)' 
    name: get_binaries
    displayName: 'Download binaries from pipeline'

  - script: |
      ls -l $HOME/test_info/
      mkdir $BASEDIR
      cd $BASEDIR
      tar zxf $(System.ArtifactsDirectory)/build/build-*.tar.gz
    name: unpack_binaries
    displayName: 'Unpack server binaries'

  # Get tools, extract repro info, convert general log into MTR and run simplification
  - script: |
      sudo apt-get update
      sudo apt-get install -y -q libdbi-perl libdbd-mysql-perl libsnappy1v5 gdb
      git clone "https://github.com/MariaDB/randgen" --branch=elenst-dev $RQG_HOME
      git clone "https://github.com/elenst/mariadb-toolbox" $TOOLBOX_DIR
      REPRO_DIR=$(System.ArtifactsDirectory)/repro
      mv $(System.ArtifactsDirectory)/test-$(TRIGGERING_ARTIFACT_ID)/repro-$(TRIGGERING_ARTIFACT_ID) $REPRO_DIR
      mysqld_repro_options=`grep 'MySQLd options' $REPRO_DIR/repro.info | sed -e "s/MySQLd options://" | sed -e "s/\$ENV_RQG_HOME/$RQG_HOME/g"`
      mtr_repro_options=`grep 'MTR options' $REPRO_DIR/repro.info | sed -e "s/MTR options://"`
      cd $BASEDIR
      patch -p 1 < $TOOLBOX_DIR/mtr/mtr_default_server.patch
      cd mysql-test
      mkdir suite/bug
      perl $TOOLBOX_DIR/scripts/mysql_log_to_mysqltest.pl $CONVERSION_OPTIONS $REPRO_DIR/mysql.log > $BASEDIR/mysql-test/suite/bug/repro.test
      echo "perl $TOOLBOX_DIR/scripts/simplify-mtr-test.pl --suitedir=$BASEDIR/mysql-test/suite/bug --testcase=repro $SIMPLIFICATION_OPTIONS --options=\"$mysqld_repro_options $mtr_repro_options $MTR_OPTIONS $MYSQLD_OPTIONS\"" > $REPRO_DIR/simplification_cmd
      if [ -n "$SEARCH_PATTERN" ] ; then
        echo `cat $REPRO_DIR/simplification_cmd` "--output=\"$SEARCH_PATTERN\"" > $REPRO_DIR/simplification_cmd
      fi
      . $REPRO_DIR/simplification_cmd
      cp suite/bug/repro.test $(Build.ArtifactStagingDirectory)/first_test.test
      tar zcf repro.output.tar.gz repro.output var/log/mysqld.1.err
      mv repro.output.tar.gz $(Build.ArtifactStagingDirectory)/
      last_test=`ls -tr $BASEDIR/mysql-test/suite/bug/repro.test.reproducible.* | tail -n 1`
      cp $last_test $REPRO_DIR/last_test.test
      echo "#######################################################################"
      if [ -n "$_TEST_COMMENT" ] ; then
        echo $_TEST_COMMENT
        echo ""
      fi
      echo "We tried to reproduce the failure happened in $TRIGGERING_ARTIFACT_ID of pipeline $TRIGGERING_PIPELINE_ID, build $TRIGGERING_BUILD_ID)"
      echo "on the server " `head -n 2 $REPRO_DIR/repro.info`
      echo "while searching for pattern $SEARCH_PATTERN"
      echo "#######################################################################"
      echo ""
    name: simplify
    displayName: 'Prepare and run simplification'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)/
      artifactName: data
    displayName: 'Store test file and output'
    condition: always()
