########################################################################
# Job to download MariaDB server binaries from FTP or build from sources
########################################################################

parameters:
  vmImage: 'Ubuntu 16.04'
  name: 'Download_or_Build_Server'
  condition: succeeded()
  dependencies: []

  SERVER_REPO: 'https://github.com/MariaDB/server'
  FTP_DOWNLOAD: 'ftp://perro.askmonty.org/public/azure'
  BUILD_LIBRARIES: 'apt-utils build-essential cmake python-dev sudo git devscripts equivs libcurl4-openssl-dev ccache python3 python3-pip curl libssl-dev libzstd-dev libevent-dev dpatch gawk gdb libboost-dev libcrack2-dev libjudy-dev libnuma-dev libsnappy-dev libxml2-dev unixodbc-dev uuid-dev fakeroot iputils-ping libncurses5-dev libbison-dev'
  EXTRA_LIBRARIES: ''

  SERVER_BRANCH: ''
  CMAKE_BUILD_TYPE: ''
  CMAKE_ASAN: ''
  CMAKE_OPTIONS: ''
  CMAKE_EXTRA_OPTIONS: ''
  BASEDIR: ''

jobs:

#-----------------------------------------------------------------------
# Try to download the server from FTP;
# if not found, then clone and build

- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  condition: ${{ parameters.condition }}
  dependsOn: ${{ parameters.dependencies }}

  steps:

  - template: ../steps/env.yml
    parameters:
      ${{ each pair in parameters }}:
        ${{ if notIn(pair.key, 'dependencies','name','condition') }}:
          ${{ pair.key }}: ${{ pair.value }}

  # Make sure that required parameters are defined
  - bash: |
      if [ -z "$ENV_SERVER_BRANCH" ]; then
        echo "##vso[task.complete result=Failed]Missing value of \"SERVER_BRANCH\""
      fi
    displayName: Check for required parameters

  # If server revision is not defined, find the head revision
  # for the given branch on Github
  - bash: | 
      rev=`git ls-remote $PAR_SERVER_REPO $ENV_SERVER_BRANCH | cut -c 1-8`
      if [ -z "$rev" ]; then
        echo "##vso[task.complete result=Failed]Could not find head revision for branch $ENV_SERVER_BRANCH"
      fi
      echo Head revision for branch $ENV_SERVER_BRANCH: $rev
      echo "##vso[task.setvariable variable=REVISION;isOutput=true]$rev"
    name: headrev
    displayName: Get head revision
    condition: and(succeeded(), eq(variables['env.SERVER_REVISION'],''))
    env:
      PAR_SERVER_REPO: '${{ parameters.SERVER_REPO }}'

  # Check if the server with this revision and cmake options
  # has already been built and stored
  - bash: |
      server_revision=${ENV_SERVER_REVISION:-$HEADREV_REVISION}
      cmake_options_hash=`echo "$ENV_CMAKE_OPTIONS" | md5sum | awk '{print $1}'`
      filename=build-$ENV_SERVER_BRANCH-$server_revision-$cmake_options_hash
      echo "Bintar filename to search for: $filename"
      echo "##vso[task.setvariable variable=BINTAR_NAME;isOutput=true]$filename"
      cd $(Build.ArtifactStagingDirectory)
      if wget $PAR_FTP_DOWNLOAD/$filename.tar.gz ; then
        echo "##vso[task.setvariable variable=BINARIES_FROM_FTP;isOutput=true]true"
      else
        echo "##vso[task.complete result=Skipped]Could not find bintar $filename"
      fi
    env:
      PAR_FTP_DOWNLOAD: '${{ parameters.FTP_DOWNLOAD }}'
    displayName: Download bintar from FTP
    name: ftp_download
    condition: succeeded()

  # If bintar was not found, install libraries, clone and build server
  - bash: |
      srcdir=$HOME/src
      builddir=$HOME/out-of-source
      
      # In case of head revision, we don't need to clone the whole history
      if [ -z "$ENV_SERVER_REVISION" ] || [ "$HEADREV_REVISION" == "$ENV_SERVER_REVISION" ] ; then
        git clone $PAR_SERVER_REPO --depth=1 --branch=$ENV_SERVER_BRANCH $srcdir
      else
        git clone $PAR_SERVER_REPO --branch=$ENV_SERVER_BRANCH $srcdir
        cd $srcdir
        git checkout $ENV_SERVER_REVISION
      fi
      sudo apt-get update
      sudo apt-get install -y -q $PAR_LIBRARIES $PAR_EXTRA_LIBRARIES
      mkdir $builddir
      cd $builddir
      cmake $srcdir $ENV_CMAKE_OPTIONS -DCMAKE_INSTALL_PREFIX=$ENV_BASEDIR
      make -j5
      make install
      cd $srcdir
      echo $ENV_SERVER_BRANCH `git log -1 --abbrev=8 --pretty="%h"` > $ENV_BASEDIR/server.info
      echo $ENV_CMAKE_OPTIONS >> $ENV_BASEDIR/server.info
    env:
      PAR_SERVER_REPO: '${{ parameters.SERVER_REPO }}'
      PAR_LIBRARIES: '${{ parameters.BUILD_LIBRARIES }}'
      PAR_EXTRA_LIBRARIES: '${{ parameters.EXTRA_LIBRARIES }}'
    condition: and(succeeded(), ne(variables['ftp_download.BINARIES_FROM_FTP'], 'true'))
    displayName: 'Clone and build server'
    name: build_server

  # Archive newly built binaries
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(env.BASEDIR)
      includeRootFolder: false
      archiveType: 'tar'
      tarCompression: 'gz'
      archiveFile:  $(Build.ArtifactStagingDirectory)/$(ftp_download.BINTAR_NAME).tar.gz
    displayName: 'Create bintar'
    name: create_bintar
    condition: and(succeeded(), ne(variables['ftp_download.BINARIES_FROM_FTP'], 'true'))

  # Store bintar as a build artifact
  # (in any case, be it downloaded or freshly built)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: 'build'
    displayName: 'Store build artifact'
    condition: succeeded()
