########################################################################
# Collect results of all test runs and print the report
########################################################################

parameters:
  vmImage: 'Ubuntu 16.04'
  condition: always()
  dependencies: []

jobs:

- job: Print_Summary
  pool:
    vmImage: ${{ parameters.vmImage }}
  condition: ${{ parameters.condition }}
  dependsOn: ${{ parameters.dependencies }}

  steps:

  - template: ../steps/env.yml

  # Collect test summaries stored as artifacts
  - task: DownloadBuildArtifacts@0
    inputs:
      downloadType: 'specific'
      itemPattern: summary-*/**/test_report
      downloadPath: $(Build.ArtifactStagingDirectory)
    displayName: 'Download test reports from artifacts'

  # Print the summary
  - script: |
      echo
      echo "####################################################################################################"
      echo "SUMMARY:"
      echo "Server $ENV_SERVER_BRANCH"
      echo $ENV_CMAKE_OPTIONS
      echo ""
      echo "Found" `ls $(Build.ArtifactStagingDirectory)/*/test_report | wc -l` "test result(s)"
      grep 'Test result: ' $(Build.ArtifactStagingDirectory)/*/test_report | sed -e 's/.*Test result: //g' | sort | uniq -c
      for f in $(Build.ArtifactStagingDirectory)/*/test_report ; do
        cat $f
      done
    displayName: TEST REPORT
    condition: ${{ parameters.condition }}

