########################################################################
# Manually coalesce environment/default variables
# The variables are processed in the following way. For any option X,
# 1) Hard default values of X and extraX parameters are set here, they
#    can be overridden by the template call;
# 2) If option 'X' is defined in the environment, the value of 'X'
#    is assigned to it, regardless the value of the parameter;
# 3) The value of 'extraX', if set, is added at the end of 'X'
# 4) Values of 'cmakeBuildType' and 'cmakeWithASAN', if set, are added
#    at the end of 'cmakeOptions'
########################################################################

parameters:
  vmImage: 'Ubuntu 16.04'
  name: 'setenv'
  taskname: 'vars'

  serverBranch: '10.4'
  rqgBranch: 'elenst-dev'
  toolboxBranch: 'master'
  
  cmakeOptions: ''
  cmakeBuildType: 'Debug'
  cmakeWithASAN: 'NO'

  rqgOptions: ''
  mysqldOptions: ''

  extraCmakeOptions: ''
  extraRqgOptions: ''
  extraMysqldOptions: ''

  baseDir: $(HOME)/server
  toolboxDir: $(HOME)/mariadb-toolbox
  rqgHome: $(HOME)/rqg
  logDir: $(HOME)/logs
  
jobs:

- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - template: ../steps/env.yml
    parameters:
      ${{ each pair in parameters }}:
        ${{ pair.key }}: ${{ pair.value }}
      name: ${{ parameters.taskname }}
  - script: printenv
    displayName: 'Print environment'
