########################################################################
# Manually coalesce environment/default variables
# The variables are processed in the following way. For any option X,
# 1) Default values of defX and extraX parameters are set here, they can
#    be overridden by the template call;
# 2) If option 'X' is not defined in the environemnt, the value of 'defX'
#    is assigned to it;
# 3) The value of 'extraX', if set, is added at the end of 'X'
# 4) Values of 'cmakeBuildType' and 'cmakeWithASAN', if set, are added
#    at the end of 'cmakeOptions'
########################################################################

parameters:
  vmImage: 'Ubuntu 16.04'
  name: 'setenv'

  defServerBranch: '10.4'
  defRQGBranch: 'elenst-dev'
  defToolboxBranch: 'master'
  
  defCmakeOptions: ''
  defCmakeBuildType: ''
  defCmakeWithASAN: ''

  defRQGOptions: ''
  defMySQLdOptions: ''

  extraCmakeOptions: ''
  extraRQGOptions: ''
  extraMySQLdOptions: ''

  defBaseDir: $(HOME)/server
  defToolboxDir: $(HOME)/mariadb-toolbox
  defRQGHome: $(HOME)/rqg
  defLogDir: $(HOME)/logs
  
  opt1: 'foo'
  opt2: 'bar'
  opt3: ''

jobs:

- job: ${{ parameters.name }}
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
    - script: |
        echo "opt1: $OPT1 opt2: $OPT2 opt3: $OPT3 opt4: $OPT4"
        echo opt1: $(opt1) opt2: $(opt2) opt3: $(opt3) opt4: $(opt4)
        echo "opt1: $OOPT1 opt2: $OOPT2 opt3: $OOPT3"
      name: vars
      env:
        DEF_SERVER_BRANCH: ${{ parameters.defServerBranch }}
        DEF_RQG_BRANCH: ${{ parameters.defRQGBranch }}
        DEF_TOOLBOX_BRANCH: ${{ parameters.defToolboxBranch }}
        DEF_CMAKE_BUILD_TYPE: ${{ parameters.defCmakeBuildType }}
        DEF_CMAKE_WITH_ASAN: ${{ parameters.defCmakeWithASAN }}
        DEF_CMAKE_OPTIONS: ${{ parameters.defCmakeOptions }}
        DEF_RQG_OPTIONS: ${{ parameters.defRQGOptions }}
        DEF_MYSQLD_OPTIONS: ${{ parameters.defMySQLdOptions }}
        EXTRA_CMAKE_OPTIONS: ${{ parameters.extraCmakeOptions }}
        EXTRA_RQG_OPTIONS: ${{ parameters.extraRQGOptions }}
        EXTRA_MYSQLD_OPTIONS: ${{ parameters.extraMySQLdOptions }}
        DEF_BASEDIR: ${{ parameters.defBaseDir }}
        DEF_TOOLBOX_DIR: ${{ parameters.defToolboxDir }}
        DEF_RQG_HOME: ${{ parameters.defRQGHome }}
        DEF_LOGDIR: ${{ parameters.defLogDir }}
        OOPT1: ${{ parameters.opt1 }}
        OOPT2: ${{ parameters.opt2 }}
        OOPT3: ${{ parameters.opt3 }}
